CREATE DATABASE GROCERYFAM;
USE GROCERYFAM;

CREATE TABLE USERS (
	UserID INT PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(100) NOT NULL,
    Password VARCHAR(250) NOT NULL
);

CREATE TABLE GROCERYITEM (
	ItemID INT PRIMARY KEY AUTO_INCREMENT,
    ItemDescription VARCHAR(250) NOT NULL,
    IsInCart BOOLEAN NOT NULL,
    IsInShoppingList BOOLEAN NOT NULL,
    DateCreated DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE GROCERYITEM ADD Qty SMALLINT NULL DEFAULT 1;
ALTER TABLE GROCERYITEM ADD UNIQUE INDEX IX_GROCERYITEM_DESC (ItemDescription(20));
ALTER TABLE GROCERYITEM ADD INDEX IX_GROCERYITEM_ISINLIST (IsInShoppingList);


CREATE TABLE GROCERYORDER (
	OrderID INT PRIMARY KEY AUTO_INCREMENT,
    Store VARCHAR(100) NULL,
    OrderDate DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDERITEM (
	OrderID INT NOT NULL,
    ItemID INT NOT NULL,
    Qty SMALLINT NULL DEFAULT 1,
    PRIMARY KEY ORDERITEM_PK (OrderID, ItemID),
    CONSTRAINT FK_ORDERITEM_ORDER FOREIGN KEY (OrderID) REFERENCES GROCERYORDER (OrderID),
    CONSTRAINT FK_ORDERITEM_ITEM FOREIGN KEY (ItemID) REFERENCES GROCERYITEM (ItemID)
);

DELIMITER $$
CREATE PROCEDURE sp_InsertNewGroceryItem
(
	OUT InsertedID INT,
	IN Param_ItemDescription VARCHAR(250)    
)
BEGIN
	INSERT INTO GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) VALUES
    (Param_ItemDescription, FALSE, TRUE);
    
    SELECT LAST_INSERT_ID() INTO InsertedID;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE sp_ProcessGroceryOrder 
( 
	IN store_name VARCHAR(100) 
)
BEGIN
	-- Declare variables
	DECLARE new_order_id INT;     
    
    START TRANSACTION;
    -- Create new order record
    INSERT INTO GROCERYORDER (Store) VALUES (store_name);
	-- Fetch the id of new record
    SELECT LAST_INSERT_ID() INTO new_order_id; 
	-- Create cross reference records between order and item
    INSERT INTO ORDERITEM (OrderID, ItemID, Qty) 
	SELECT new_order_id, ItemID, Qty 
    FROM GROCERYITEM 
    WHERE IsInShoppingList = TRUE AND IsInCart = TRUE;
	-- Reset the items that were in the cart
    UPDATE GROCERYITEM SET IsInCart = FALSE, IsInShoppingList = FALSE, Qty = 1 WHERE IsInShoppingList = TRUE AND IsInCart = TRUE;    
    COMMIT;
END$$
DELIMITER ;