insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Cookies - Amaretto', true, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Yeast Dry - Fleischman', false, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Mix - Cocktail Ice Cream', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Roe - White Fish', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Turkey - Breast, Double', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Langers - Ruby Red Grapfruit', true, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Energy - Boo - Koo', true, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Corn Meal', false, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Pasta - Penne, Rigate, Dry', true, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Pork - Belly Fresh', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Beans - Yellow', false, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Wooden Mop Handle', true, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Lychee - Canned', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Wine - Conde De Valdemar', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Schnappes - Peach, Walkers', false, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Cheese - Montery Jack', true, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Tea - Lemon Scented', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Aspic - Clear', false, false);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Ginger - Ground', false, true);
insert into GROCERYITEM (ItemDescription, IsInCart, IsInShoppingList) values ('Energy Drink - Redbull 355ml', false, false);
